#!/bin/sh 
ENV_TOP=/home/znilpau/mnt
# NFSCMD="mount seliisahs21001:/vols0407/puppetenv ${ENV_TOP}"
USER=znilpau
SSHKEY=/home/znilpau/.ssh/id_rsa
GERRIT=ssh://${USER}@gerritmirror.lmera.ericsson.se/puppet
export GERRIT
REPOS=(hiera-gic modules-eis modules-gic)
ORKDIR=${ENV_TOP}/modules-staging
CHECK_INTERVAL=13
# Don't forget to change below thins line if you move this dir
HERE=/home/znilpau/update-staging
