#!/bin/sh 
ENV_TOP=/etc/puppet/environments
# NFSCMD="mount seliisahs21001:/vols0407/puppetenv ${ENV_TOP}"
USER=elxuxrepo
SSHKEY=/home/${USER}/.ssh/id_rsa
GERRIT=ssh://${USER}@gerrit.ericsson.se:29418/puppet
export GERRIT
REPOS=(hiera-gic modules-eis modules-gic)
BRANCHES=(master staging staging)
ORKDIR=${ENV_TOP}/modules_staging
CHECK_INTERVAL=13
KICKDIR=${ENV_TOP}/modules_staging/modules-gic
TMPDOMAIN=rnd.ki.sw.ericsson.se
KICKPUPPET=${KICKDIR}/update_puppet_modules.sh
# Don't forget to change below thins line if you move this dir
HERE=/etc/puppet/environments/modules_staging/bin
