#!/bin/bash
. /home/znilpau/update-staging/settings

umask 022

cd $ORKDIR
if [ $? -ne 0 ] ; then # )/(#/¤#()//
  # So if we got here either dir is not mounted or does not exist
  # See if it is nfs and can be mounted
  if [ -n "$NFSCMD" ] ; then
   $NFSCMD
  else 
    mkdir -p $ORKDIR || exit 16
  fi
  cd $ORKDIR
  if [ $? -ne 0 ] ; then # Ok, might be a local dir and this is first run
    exit 17
  fi
fi

GIT_VERS=`git --version | awk '{print $NF}' | awk -F. '{print $1$2$3}'`
if [ $GIT_VERS -ge 230 ] ; then 
  export GIT_SSH_COMMAND="ssh -i ${SSHKEY}"
else
  export GIT_SSH="${HERE}/ssh-wrap"
fi
for repo in ${REPOS[@]} ; do
  if ! echo $@ | grep skip_$repo ; then
    cd $repo
    if [ $? -ne 0 ] ; then # probably first run
      echo $GERRIT
      echo "git-ssh " $GIT_SSH
      git clone  ${GERRIT}/$repo
      cd $repo || exit 19
    fi
    git fetch origin
    UPDATES=`git log HEAD..origin/staging`
    test -n $UPDATES && git pull origin staging
    cd ..
  fi
done 
